//! Relay Sessions: the continuity/handoff unit.
//!
//! A *project* (a repository) may hold many Relay Sessions. A Relay Session is one logical
//! conversation/workstream with a stable id of Relay's own, independent of any provider-native
//! session id (a Claude → Codex handoff keeps the Relay Session and changes the native one).
//!
//! State on disk, per project (`<state>/projects/<project id>/`):
//!
//! ```text
//! registry.lock              short-lived lock for creating sessions / native-id uniqueness
//! sessions/<relay session id>/
//!     session.json           the durable record (survives the provider process)
//!     lease.json             the ACTIVE lease — exists only while Relay supervises a live process
//!     orchestration.lock     the per-session transaction lock (resume, adopt, handoff, recovery)
//!     handoffs/, current_transaction.json, automation_state.json, provider_args.json, control/
//! ```
//!
//! A session with a lease is ACTIVE; without one it is DORMANT (remembered, not owned). The
//! invariant is one active owner per Relay Session — not one writer per project. Nothing here holds
//! a lock for the lifetime of a provider process.

use std::{
    fs,
    io::Read as _,
    path::{Path, PathBuf},
    time::{Duration, Instant},
};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::{
    AtomicWrite, Error, FsAtomicWriter, ProfileName, RelayPaths, Result,
    handoff::{LeaseStore, OrchestrationLock, ProjectId, WorkingStateStore, WriterLease},
};

const RECORD_VERSION: u32 = 1;
const RECORD_FILE: &str = "session.json";
const LEASE_FILE: &str = "lease.json";
const LOCK_FILE: &str = "orchestration.lock";
const REGISTRY_LOCK: &str = "registry.lock";
const MIGRATION_INTENT: &str = "migration.json";
/// How long a metadata operation waits for the (short-lived) registry lock.
const REGISTRY_WAIT: Duration = Duration::from_secs(15);

/// A Relay Session id: a random UUID (v4 shape), generated by Relay. Safe as a path component.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct RelaySessionId(String);

impl RelaySessionId {
    pub fn generate() -> Result<Self> {
        let mut bytes = [0_u8; 16];
        fs::File::open("/dev/urandom")
            .and_then(|mut file| file.read_exact(&mut bytes))
            .map_err(|source| Error::Io {
                path: PathBuf::from("/dev/urandom"),
                source,
            })?;
        Ok(Self::from_bytes(bytes))
    }

    fn from_bytes(mut bytes: [u8; 16]) -> Self {
        bytes[6] = (bytes[6] & 0x0f) | 0x40;
        bytes[8] = (bytes[8] & 0x3f) | 0x80;
        let hex: String = bytes.iter().map(|byte| format!("{byte:02x}")).collect();
        Self(format!(
            "{}-{}-{}-{}-{}",
            &hex[0..8],
            &hex[8..12],
            &hex[12..16],
            &hex[16..20],
            &hex[20..32]
        ))
    }

    /// Only the shape Relay generates is accepted, so it is safe as a path component.
    pub fn parse(value: &str) -> Result<Self> {
        let parts: Vec<&str> = value.split('-').collect();
        let valid = parts.len() == 5
            && [8, 4, 4, 4, 12].iter().zip(&parts).all(|(len, part)| {
                part.len() == *len && part.bytes().all(|b| b.is_ascii_hexdigit())
            });
        if valid {
            Ok(Self(value.to_ascii_lowercase()))
        } else {
            Err(Error::RelaySessionNotFound(value.to_owned()))
        }
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// The first eight characters, for display.
    #[must_use]
    pub fn short(&self) -> &str {
        &self.0[..8]
    }
}

impl std::fmt::Display for RelaySessionId {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(formatter)
    }
}

/// Behavioral intent for a Relay Session — never a permission grant. See module docs and
/// `docs/automatic-handoff.md`: this decides only whether a target should ask "would you like me
/// to continue?" after a handoff, never what a provider process is allowed to do to the
/// filesystem/network/destructive actions. Provider-specific sandbox/permission behavior is
/// completely orthogonal to this and must never be inferred from it.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExecutionIntent {
    /// Normal conversational behavior: the agent may ask before continuing, as usual.
    #[default]
    Interactive,
    /// Continue pursuing the current task without asking the user whether to continue merely
    /// because a handoff occurred. Does not suppress stopping for a genuine blocker (missing
    /// credential/information, an action needing explicit authorization, or unsafe/ambiguous
    /// continuation) — see [`super::continuity::render_autonomous_notice`].
    Autonomous,
}

/// The durable record. `last_profile` and `native_session_id` are *history* while the session is
/// dormant — never an active owner.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RelaySessionRecord {
    pub version: u32,
    pub relay_session_id: RelaySessionId,
    pub project_id: ProjectId,
    pub created_unix_ms: u64,
    pub last_activity_unix_ms: u64,
    pub last_profile: ProfileName,
    /// `claude` / `codex`, when known (a display hint; the profile registry is authoritative).
    #[serde(default)]
    pub provider: Option<String>,
    /// The provider-native session/thread id most recently associated with this session.
    #[serde(default)]
    pub native_session_id: Option<String>,
    /// True until a real conversation is known to have been persisted; a provisional session that
    /// ends is removed instead of remembered.
    #[serde(default)]
    pub provisional: bool,
    /// Set once, at session creation, from the launching command's own flag — never changed by a
    /// handoff. An old record predating this field safely deserializes as `Interactive`, the
    /// least-surprising existing behavior.
    #[serde(default)]
    pub execution_intent: ExecutionIntent,
}

impl RelaySessionRecord {
    #[must_use]
    pub fn new(
        relay_session_id: RelaySessionId,
        project_id: ProjectId,
        last_profile: ProfileName,
        provider: Option<String>,
        native_session_id: Option<String>,
        provisional: bool,
        now_unix_ms: u64,
    ) -> Self {
        Self {
            version: RECORD_VERSION,
            relay_session_id,
            project_id,
            created_unix_ms: now_unix_ms,
            last_activity_unix_ms: now_unix_ms,
            last_profile,
            provider,
            native_session_id,
            provisional,
            execution_intent: ExecutionIntent::default(),
        }
    }

    /// Overrides the execution intent set by [`Self::new`] — a separate step so every existing
    /// call site that has no opinion on autonomy keeps compiling unchanged and keeps the safe
    /// `Interactive` default.
    #[must_use]
    pub const fn with_execution_intent(mut self, intent: ExecutionIntent) -> Self {
        self.execution_intent = intent;
        self
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SessionState {
    /// A lease exists: Relay supervises (or must assume it supervises) a live provider process.
    Active,
    /// Remembered, not owned.
    Dormant,
}

/// A record together with its lease, if any.
#[derive(Clone, Debug)]
pub struct RelaySessionView {
    pub record: RelaySessionRecord,
    pub lease: Option<WriterLease>,
}

impl RelaySessionView {
    #[must_use]
    pub const fn state(&self) -> SessionState {
        if self.lease.is_some() {
            SessionState::Active
        } else {
            SessionState::Dormant
        }
    }

    /// The native id currently in force (the lease's while active, else the last known).
    #[must_use]
    pub fn native_session_id(&self) -> Option<&str> {
        self.lease
            .as_ref()
            .map(|lease| lease.session_id.as_str())
            .or(self.record.native_session_id.as_deref())
    }

    /// The owner while active; the last profile (history) otherwise.
    #[must_use]
    pub fn profile(&self) -> &ProfileName {
        self.lease
            .as_ref()
            .map_or(&self.record.last_profile, |lease| &lease.owner_profile)
    }
}

pub struct SessionStore<'a> {
    paths: &'a RelayPaths,
    project_id: ProjectId,
}

fn io_error(path: &Path, source: std::io::Error) -> Error {
    Error::Io {
        path: path.to_path_buf(),
        source,
    }
}

impl<'a> SessionStore<'a> {
    #[must_use]
    pub fn new(paths: &'a RelayPaths, project_id: ProjectId) -> Self {
        Self { paths, project_id }
    }

    #[must_use]
    pub fn project_id(&self) -> &ProjectId {
        &self.project_id
    }

    #[must_use]
    pub fn project_dir(&self) -> PathBuf {
        self.paths.project_state_dir(&self.project_id)
    }

    #[must_use]
    pub fn session_dir(&self, id: &RelaySessionId) -> PathBuf {
        self.project_dir().join("sessions").join(id.as_str())
    }

    #[must_use]
    pub fn lease_store(&self, id: &RelaySessionId) -> LeaseStore {
        LeaseStore::at_path(self.session_dir(id).join(LEASE_FILE))
    }

    #[must_use]
    pub fn session_lock(&self, id: &RelaySessionId) -> OrchestrationLock {
        OrchestrationLock::at_path(self.session_dir(id).join(LOCK_FILE))
    }

    /// Issue #5: the durable, provider-neutral, advisory working-state store for this session —
    /// see [`WorkingStateStore`]'s own docs. A session with no `working_state.json` yet is
    /// normal; nothing here creates the file until the first `relay state update`.
    #[must_use]
    pub fn working_state(&self, id: &RelaySessionId) -> WorkingStateStore {
        WorkingStateStore::at_session_dir(self.session_dir(id))
    }

    /// Runs `body` under the project's short-lived registry lock, waiting briefly if another Relay
    /// process holds it. Never held for the lifetime of a provider process.
    pub fn with_registry_lock<T>(&self, body: impl FnOnce() -> Result<T>) -> Result<T> {
        let dir = self.project_dir();
        fs::create_dir_all(&dir).map_err(|source| io_error(&dir, source))?;
        let lock = OrchestrationLock::at_path(dir.join(REGISTRY_LOCK));
        let started = Instant::now();
        let mut body = Some(body);
        loop {
            match lock.try_with(|| (body.take().expect("body runs once"))()) {
                Err(Error::OrchestrationLockHeld) if started.elapsed() < REGISTRY_WAIT => {
                    // `body` was not consumed when the lock was refused.
                    std::thread::sleep(Duration::from_millis(25));
                }
                other => return other,
            }
        }
    }

    // ---- reading -------------------------------------------------------------------------

    pub fn load_record(&self, id: &RelaySessionId) -> Result<Option<RelaySessionRecord>> {
        let path = self.session_dir(id).join(RECORD_FILE);
        match fs::read(&path) {
            Ok(bytes) => {
                let record: RelaySessionRecord =
                    serde_json::from_slice(&bytes).map_err(|_| Error::CorruptedState)?;
                if record.version != RECORD_VERSION || &record.relay_session_id != id {
                    return Err(Error::CorruptedState);
                }
                Ok(Some(record))
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(source) => Err(io_error(&path, source)),
        }
    }

    pub fn view(&self, id: &RelaySessionId) -> Result<Option<RelaySessionView>> {
        let Some(record) = self.load_record(id)? else {
            return Ok(None);
        };
        let lease = self.lease_store(id).load()?;
        Ok(Some(RelaySessionView { record, lease }))
    }

    /// Every session of this project, migrating legacy single-lease state first. Newest activity
    /// first.
    pub fn list(&self) -> Result<Vec<RelaySessionView>> {
        self.ensure_migrated()?;
        let root = self.project_dir().join("sessions");
        let entries = match fs::read_dir(&root) {
            Ok(entries) => entries,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
            Err(source) => return Err(io_error(&root, source)),
        };
        let mut views = Vec::new();
        for entry in entries.flatten() {
            let Some(name) = entry.file_name().to_str().map(str::to_owned) else {
                continue;
            };
            let Ok(id) = RelaySessionId::parse(&name) else {
                continue;
            };
            if let Some(view) = self.view(&id)? {
                views.push(view);
            }
        }
        views.sort_by(|left, right| {
            right
                .record
                .last_activity_unix_ms
                .cmp(&left.record.last_activity_unix_ms)
                .then_with(|| {
                    left.record
                        .relay_session_id
                        .cmp(&right.record.relay_session_id)
                })
        });
        Ok(views)
    }

    /// Resolves a full id or an unambiguous prefix (at least four characters).
    pub fn resolve(&self, selector: &str) -> Result<RelaySessionView> {
        let selector = selector.trim().to_ascii_lowercase();
        let views = self.list()?;
        let matching: Vec<&RelaySessionView> = views
            .iter()
            .filter(|view| {
                view.record.relay_session_id.as_str() == selector
                    || (selector.len() >= 4
                        && view.record.relay_session_id.as_str().starts_with(&selector))
            })
            .collect();
        match matching.as_slice() {
            [only] => Ok((*only).clone()),
            [] => Err(Error::RelaySessionNotFound(selector)),
            _ => Err(Error::RelaySessionAmbiguous(selector)),
        }
    }

    /// The session (active or dormant) currently associated with a provider-native session id.
    pub fn find_by_native(&self, native: &str) -> Result<Option<RelaySessionView>> {
        Ok(self
            .list()?
            .into_iter()
            .find(|view| view.native_session_id() == Some(native)))
    }

    // ---- writing ---------------------------------------------------------------------------

    pub fn save_record(&self, record: &RelaySessionRecord) -> Result<()> {
        let dir = self.session_dir(&record.relay_session_id);
        fs::create_dir_all(&dir).map_err(|source| io_error(&dir, source))?;
        let bytes = serde_json::to_vec_pretty(record).map_err(|_| Error::SerializationFailed)?;
        FsAtomicWriter.write_atomic(&dir.join(RECORD_FILE), &bytes)
    }

    /// Removes a whole session directory (provisional cleanup). Refuses while a lease exists.
    pub fn remove(&self, id: &RelaySessionId) -> Result<()> {
        if self.lease_store(id).load()?.is_some() {
            return Err(Error::RelaySessionActive(id.to_string()));
        }
        let dir = self.session_dir(id);
        match fs::remove_dir_all(&dir) {
            Ok(()) => Ok(()),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(source) => Err(io_error(&dir, source)),
        }
    }

    /// Fails when `native` is the native session of any *other* active Relay Session of this
    /// project. Call inside the registry lock.
    fn ensure_native_not_active_elsewhere(
        &self,
        native: &str,
        except: &RelaySessionId,
    ) -> Result<()> {
        let root = self.project_dir().join("sessions");
        let Ok(entries) = fs::read_dir(&root) else {
            return Ok(());
        };
        for entry in entries.flatten() {
            let Some(name) = entry.file_name().to_str().map(str::to_owned) else {
                continue;
            };
            let Ok(id) = RelaySessionId::parse(&name) else {
                continue;
            };
            if &id == except {
                continue;
            }
            if let Some(lease) = self.lease_store(&id).load()?
                && lease.session_id == native
            {
                return Err(Error::NativeSessionAlreadyActive(id.short().to_owned()));
            }
        }
        Ok(())
    }

    /// Creates a Relay Session and its first active lease in one registry-locked step. Refuses
    /// when the same native session is already active in another Relay Session.
    pub fn create_active(&self, record: &RelaySessionRecord, lease: &WriterLease) -> Result<()> {
        self.ensure_migrated()?;
        self.with_registry_lock(|| {
            self.ensure_native_not_active_elsewhere(&lease.session_id, &record.relay_session_id)?;
            self.save_record(record)?;
            self.lease_store(&record.relay_session_id).save(lease)
        })
    }

    /// Gives a dormant session a new active lease (resume, re-adoption). Refuses when the session
    /// already has one or the native session is active elsewhere.
    pub fn activate(&self, id: &RelaySessionId, lease: &WriterLease) -> Result<()> {
        self.with_registry_lock(|| {
            self.ensure_native_not_active_elsewhere(&lease.session_id, id)?;
            let store = self.lease_store(id);
            if store.load()?.is_some() {
                return Err(Error::RelaySessionActive(id.short().to_owned()));
            }
            store.save(lease)?;
            if let Some(mut record) = self.load_record(id)? {
                record.last_profile = lease.owner_profile.clone();
                record.native_session_id = Some(lease.session_id.clone());
                record.provisional = false;
                self.save_record(&record)?;
            }
            Ok(())
        })
    }

    /// Ends the active lease: the last owner and native id become history on the record, and the
    /// session is dormant. `remove_session` deletes it outright instead (a provisional session
    /// whose conversation was never persisted). The caller has proven the owner process is gone.
    pub fn release(
        &self,
        id: &RelaySessionId,
        now_unix_ms: u64,
        remove_session: bool,
    ) -> Result<()> {
        self.with_registry_lock(|| {
            let store = self.lease_store(id);
            let lease = store.load()?;
            store.clear()?;
            if remove_session {
                return self.remove(id);
            }
            if let (Some(lease), Some(mut record)) = (lease, self.load_record(id)?) {
                record.last_profile = lease.owner_profile;
                record.native_session_id = Some(lease.session_id);
                record.last_activity_unix_ms = now_unix_ms;
                record.provisional = false;
                self.save_record(&record)?;
            }
            Ok(())
        })
    }

    // ---- migration of the old one-lease-per-project layout --------------------------------

    /// Turns the legacy single project lease (and its journals, provider arguments, ledger and
    /// control directory) into exactly one Relay Session. Deterministic (the session id is derived
    /// from the old lease), atomic per step, crash-safe (an intent file is written first and the
    /// steps are idempotent) and idempotent.
    pub fn ensure_migrated(&self) -> Result<()> {
        let dir = self.project_dir();
        let legacy_lease = dir.join(LEASE_FILE);
        let intent_path = dir.join(MIGRATION_INTENT);
        if !legacy_lease.exists() && !intent_path.exists() {
            return Ok(());
        }
        self.with_registry_lock(|| {
            if !legacy_lease.exists() && !intent_path.exists() {
                return Ok(());
            }
            let intent: MigrationIntent = if intent_path.exists() {
                serde_json::from_slice(
                    &fs::read(&intent_path).map_err(|source| io_error(&intent_path, source))?,
                )
                .map_err(|_| Error::CorruptedState)?
            } else {
                let lease = LeaseStore::at_path(legacy_lease.clone())
                    .load()?
                    .ok_or(Error::CorruptedLease)?;
                let mut hasher = Sha256::new();
                hasher.update(b"relay-legacy-session|");
                hasher.update(self.project_id.as_str().as_bytes());
                hasher.update(b"|");
                hasher.update(lease.session_id.as_bytes());
                hasher.update(b"|");
                hasher.update(lease.acquired_unix_ms.to_le_bytes());
                let digest = hasher.finalize();
                let mut bytes = [0_u8; 16];
                bytes.copy_from_slice(&digest[..16]);
                let intent = MigrationIntent {
                    relay_session_id: RelaySessionId::from_bytes(bytes),
                    last_profile: lease.owner_profile.clone(),
                    native_session_id: lease.session_id.clone(),
                    acquired_unix_ms: lease.acquired_unix_ms,
                };
                let text =
                    serde_json::to_vec_pretty(&intent).map_err(|_| Error::SerializationFailed)?;
                FsAtomicWriter.write_atomic(&intent_path, &text)?;
                intent
            };
            let session_dir = self.session_dir(&intent.relay_session_id);
            fs::create_dir_all(&session_dir).map_err(|source| io_error(&session_dir, source))?;
            for name in [
                LEASE_FILE,
                "handoffs",
                "current_transaction.json",
                "provider_args.json",
                "automation_state.json",
                "control",
            ] {
                let from = dir.join(name);
                let to = session_dir.join(name);
                if from.exists() && !to.exists() {
                    fs::rename(&from, &to).map_err(|source| io_error(&from, source))?;
                }
            }
            if !session_dir.join(RECORD_FILE).exists() {
                self.save_record(&RelaySessionRecord::new(
                    intent.relay_session_id.clone(),
                    self.project_id.clone(),
                    intent.last_profile.clone(),
                    None,
                    Some(intent.native_session_id.clone()),
                    false,
                    intent.acquired_unix_ms,
                ))?;
            }
            match fs::remove_file(&intent_path) {
                Ok(()) => Ok(()),
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
                Err(source) => Err(io_error(&intent_path, source)),
            }
        })
    }
}

#[derive(Serialize, Deserialize)]
struct MigrationIntent {
    relay_session_id: RelaySessionId,
    last_profile: ProfileName,
    native_session_id: String,
    acquired_unix_ms: u64,
}

#[cfg(test)]
mod tests {
    use tempfile::tempdir;

    use super::*;
    use crate::handoff::{ProcessIdentity, TransactionId};

    fn paths(root: &Path) -> RelayPaths {
        RelayPaths::new(root.join("config"), root.join("state")).expect("paths")
    }

    fn lease(project: &ProjectId, profile: &str, native: &str) -> WriterLease {
        WriterLease::new(
            project.clone(),
            ProfileName::new(profile).expect("profile"),
            ProcessIdentity::current(),
            native.to_owned(),
            TransactionId::generate(),
            10,
        )
    }

    fn record(project: &ProjectId, profile: &str, native: &str) -> RelaySessionRecord {
        RelaySessionRecord::new(
            RelaySessionId::generate().expect("id"),
            project.clone(),
            ProfileName::new(profile).expect("profile"),
            Some("claude".to_owned()),
            Some(native.to_owned()),
            false,
            10,
        )
    }

    fn project() -> ProjectId {
        ProjectId::for_canonical_path(Path::new("/work/repo")).expect("project")
    }

    #[test]
    fn several_sessions_of_one_project_and_one_profile_are_active_together() {
        let root = tempdir().expect("root");
        let paths = paths(root.path());
        let store = SessionStore::new(&paths, project());
        for native in ["n1", "n2", "n3"] {
            let record = record(&project(), "megan", native);
            store
                .create_active(&record, &lease(&project(), "megan", native))
                .expect("create");
        }
        let views = store.list().expect("list");
        assert_eq!(views.len(), 3);
        assert!(
            views
                .iter()
                .all(|view| view.state() == SessionState::Active)
        );
        assert!(views.iter().all(|view| view.profile().as_str() == "megan"));
    }

    #[test]
    fn the_same_native_session_cannot_be_active_in_two_relay_sessions() {
        let root = tempdir().expect("root");
        let paths = paths(root.path());
        let store = SessionStore::new(&paths, project());
        store
            .create_active(
                &record(&project(), "megan", "n1"),
                &lease(&project(), "megan", "n1"),
            )
            .expect("first");
        let error = store
            .create_active(
                &record(&project(), "erika", "n1"),
                &lease(&project(), "erika", "n1"),
            )
            .expect_err("duplicate native");
        assert_eq!(error.code(), "native_session_already_active");
        assert_eq!(store.list().expect("list").len(), 1);
    }

    #[test]
    fn a_session_cannot_hold_two_leases_and_release_makes_it_dormant_with_history() {
        let root = tempdir().expect("root");
        let paths = paths(root.path());
        let store = SessionStore::new(&paths, project());
        let record = record(&project(), "megan", "n1");
        let id = record.relay_session_id.clone();
        store
            .create_active(&record, &lease(&project(), "megan", "n1"))
            .expect("create");
        let error = store
            .activate(&id, &lease(&project(), "erika", "n1"))
            .expect_err("already active");
        assert_eq!(error.code(), "relay_session_active");
        store.release(&id, 99, false).expect("release");
        let view = store.view(&id).expect("view").expect("exists");
        assert_eq!(view.state(), SessionState::Dormant);
        assert_eq!(view.record.last_profile.as_str(), "megan");
        assert_eq!(view.record.last_activity_unix_ms, 99);
        // Reactivation on another profile: same Relay Session, new lease.
        store
            .activate(&id, &lease(&project(), "erika", "n1"))
            .expect("reactivate");
        assert_eq!(
            store.view(&id).unwrap().unwrap().profile().as_str(),
            "erika"
        );
    }

    #[test]
    fn releasing_a_provisional_session_removes_it() {
        let root = tempdir().expect("root");
        let paths = paths(root.path());
        let store = SessionStore::new(&paths, project());
        let mut record = record(&project(), "megan", "n1");
        record.provisional = true;
        let id = record.relay_session_id.clone();
        store
            .create_active(&record, &lease(&project(), "megan", "n1"))
            .expect("create");
        store.release(&id, 5, true).expect("release");
        assert!(store.list().expect("list").is_empty());
    }

    #[test]
    fn selectors_resolve_by_prefix_and_refuse_ambiguity() {
        let root = tempdir().expect("root");
        let paths = paths(root.path());
        let store = SessionStore::new(&paths, project());
        let a = record(&project(), "megan", "n1");
        store
            .create_active(&a, &lease(&project(), "megan", "n1"))
            .expect("a");
        let found = store
            .resolve(&a.relay_session_id.as_str()[..6])
            .expect("prefix");
        assert_eq!(found.record.relay_session_id, a.relay_session_id);
        assert_eq!(
            store.resolve("zzzz").expect_err("none").code(),
            "relay_session_not_found"
        );
    }

    fn write_legacy(paths: &RelayPaths, profile: &str, native: &str) -> PathBuf {
        let dir = paths.project_state_dir(&project());
        fs::create_dir_all(dir.join("handoffs")).expect("dirs");
        LeaseStore::at_path(dir.join("lease.json"))
            .save(&lease(&project(), profile, native))
            .expect("lease");
        fs::write(
            dir.join("provider_args.json"),
            "{\"claude\":[\"--model\",\"opus\"]}",
        )
        .expect("args");
        fs::write(dir.join("handoffs/ho-1.json"), "{}").expect("journal");
        fs::write(dir.join("current_transaction.json"), "ho-1").expect("pointer");
        dir
    }

    #[test]
    fn a_legacy_project_lease_becomes_exactly_one_active_session_and_is_idempotent() {
        let root = tempdir().expect("root");
        let paths = paths(root.path());
        let dir = write_legacy(&paths, "megan", "native-1");
        let store = SessionStore::new(&paths, project());
        let views = store.list().expect("migrates");
        assert_eq!(views.len(), 1);
        let view = &views[0];
        assert_eq!(
            view.state(),
            SessionState::Active,
            "a live lease stays active"
        );
        assert_eq!(view.native_session_id(), Some("native-1"));
        let session_dir = store.session_dir(&view.record.relay_session_id);
        assert!(session_dir.join("handoffs/ho-1.json").exists());
        assert!(session_dir.join("current_transaction.json").exists());
        assert!(
            fs::read_to_string(session_dir.join("provider_args.json"))
                .unwrap()
                .contains("opus")
        );
        assert!(!dir.join("lease.json").exists());
        // Again: no duplication, same id.
        let again = store.list().expect("second");
        assert_eq!(again.len(), 1);
        assert_eq!(
            again[0].record.relay_session_id,
            view.record.relay_session_id
        );
    }

    #[test]
    fn an_interrupted_migration_resumes_to_the_same_single_session() {
        let root = tempdir().expect("root");
        let paths = paths(root.path());
        let dir = write_legacy(&paths, "erika", "native-2");
        let store = SessionStore::new(&paths, project());
        // Simulate a crash after the intent was written and the lease moved, before the rest.
        let first = store.list().expect("migrate once");
        let id = first[0].record.relay_session_id.clone();
        let session_dir = store.session_dir(&id);
        // Undo the tail of the migration: record gone, intent back, one file back at the root.
        fs::remove_file(session_dir.join("session.json")).expect("drop record");
        fs::rename(
            session_dir.join("provider_args.json"),
            dir.join("provider_args.json"),
        )
        .expect("move back");
        fs::rename(session_dir.join("lease.json"), dir.join("lease.json")).expect("lease back");
        let again = store.list().expect("recovers");
        assert_eq!(again.len(), 1);
        assert_eq!(again[0].record.relay_session_id, id, "deterministic id");
        assert_eq!(
            again[0].record.native_session_id.as_deref(),
            Some("native-2")
        );
        assert!(session_dir.join("provider_args.json").exists());
    }

    #[test]
    fn a_new_record_defaults_to_interactive() {
        let record = record(&project(), "megan", "n1");
        assert_eq!(record.execution_intent, ExecutionIntent::Interactive);
    }

    #[test]
    fn with_execution_intent_overrides_the_default() {
        let record =
            record(&project(), "megan", "n1").with_execution_intent(ExecutionIntent::Autonomous);
        assert_eq!(record.execution_intent, ExecutionIntent::Autonomous);
    }

    #[test]
    fn an_old_record_without_execution_intent_deserializes_as_interactive() {
        // Exactly the shape a pre-this-change `session.json` has on disk: no `execution_intent`
        // key at all. `#[serde(deny_unknown_fields)]` only rejects EXTRA keys, never missing ones
        // with a `#[serde(default)]`, so this must still parse.
        let old_json = serde_json::json!({
            "version": 1,
            "relay_session_id": RelaySessionId::generate().expect("id").as_str(),
            "project_id": project().as_str(),
            "created_unix_ms": 10,
            "last_activity_unix_ms": 10,
            "last_profile": "megan",
            "provider": "claude",
            "native_session_id": "n1",
            "provisional": false,
        });
        let record: RelaySessionRecord =
            serde_json::from_value(old_json).expect("old record without the new field parses");
        assert_eq!(record.execution_intent, ExecutionIntent::Interactive);
    }

    #[test]
    fn execution_intent_persists_through_release_and_reactivate() {
        let root = tempdir().expect("root");
        let paths = paths(root.path());
        let store = SessionStore::new(&paths, project());
        let record =
            record(&project(), "megan", "n1").with_execution_intent(ExecutionIntent::Autonomous);
        let id = record.relay_session_id.clone();
        store
            .create_active(&record, &lease(&project(), "megan", "n1"))
            .expect("create");
        // The session goes dormant (source stopped)...
        store.release(&id, 20, false).expect("release");
        let dormant = store.load_record(&id).expect("load").expect("exists");
        assert_eq!(dormant.execution_intent, ExecutionIntent::Autonomous);
        // ...then a handoff hands it to a different profile/native session entirely.
        store
            .activate(&id, &lease(&project(), "bob", "n2"))
            .expect("activate");
        let after_handoff = store.load_record(&id).expect("load").expect("exists");
        assert_eq!(after_handoff.execution_intent, ExecutionIntent::Autonomous);
        assert_eq!(after_handoff.last_profile.as_str(), "bob");
    }
}
