use std::{
    fmt,
    time::{SystemTime, UNIX_EPOCH},
};

use serde::{Deserialize, Serialize};

use crate::{Error, Result};

/// A durable handoff transaction id. Generated by Relay, never operator-chosen, so it can be
/// trusted as a filesystem path component without separate validation at every use site.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Serialize, Deserialize)]
#[serde(transparent)]
pub struct TransactionId(String);

impl TransactionId {
    #[must_use]
    pub fn generate() -> Self {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|duration| duration.as_nanos())
            .unwrap_or_default();
        Self(format!("ho-{nanos:x}-{}", std::process::id()))
    }

    /// Parses an operator-supplied transaction id (e.g. from `relay recover <id>`). Only the
    /// shape Relay itself generates is accepted, so it is safe to use directly as a path
    /// component afterward.
    pub fn parse(value: &str) -> Result<Self> {
        let valid = value.len() <= 128
            && !value.is_empty()
            && value
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-');
        if valid {
            Ok(Self(value.to_owned()))
        } else {
            Err(Error::InvalidTransactionId(value.to_owned()))
        }
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for TransactionId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

/// Mirrors docs/architecture.md's handoff state machine. `Failed` and `RecoveryRequired` are
/// reachable from any in-progress state; `Complete` is reachable only from `TargetVerified`.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(tag = "state", rename_all = "SCREAMING_SNAKE_CASE")]
pub enum HandoffState {
    Preparing,
    Checkpointed,
    SourceStopping,
    SourceStopped,
    SessionTransferring,
    SessionTransferred,
    TargetStarting,
    TargetVerified,
    Complete,
    Failed { phase: FailedPhase, reason: String },
    RecoveryRequired { reason: String },
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum FailedPhase {
    Prepare,
    Stop,
    Transfer,
    TargetStart,
    Verify,
}

impl HandoffState {
    #[must_use]
    pub const fn is_terminal(&self) -> bool {
        matches!(self, Self::Complete | Self::Failed { .. })
    }

    #[must_use]
    pub const fn is_in_progress(&self) -> bool {
        !self.is_terminal() && !matches!(self, Self::RecoveryRequired { .. })
    }

    /// The ordinary forward sequence. `Failed`/`RecoveryRequired` are allowed from any
    /// non-terminal state and are checked separately by [`HandoffState::can_advance_to`].
    fn ordinary_successor(&self) -> Option<Self> {
        match self {
            Self::Preparing => Some(Self::Checkpointed),
            Self::Checkpointed => Some(Self::SourceStopping),
            Self::SourceStopping => Some(Self::SourceStopped),
            Self::SourceStopped => Some(Self::SessionTransferring),
            Self::SessionTransferring => Some(Self::SessionTransferred),
            Self::SessionTransferred => Some(Self::TargetStarting),
            Self::TargetStarting => Some(Self::TargetVerified),
            Self::TargetVerified => Some(Self::Complete),
            Self::Complete | Self::Failed { .. } | Self::RecoveryRequired { .. } => None,
        }
    }

    #[must_use]
    pub fn can_advance_to(&self, next: &Self) -> bool {
        if self.is_terminal() {
            return false;
        }
        if matches!(next, Self::Failed { .. } | Self::RecoveryRequired { .. }) {
            return true;
        }
        self.ordinary_successor().as_ref() == Some(next)
    }
}

#[cfg(test)]
mod tests {
    use super::{FailedPhase, HandoffState, TransactionId};

    #[test]
    fn ordinary_sequence_is_linear_and_exclusive() {
        let sequence = [
            HandoffState::Preparing,
            HandoffState::Checkpointed,
            HandoffState::SourceStopping,
            HandoffState::SourceStopped,
            HandoffState::SessionTransferring,
            HandoffState::SessionTransferred,
            HandoffState::TargetStarting,
            HandoffState::TargetVerified,
            HandoffState::Complete,
        ];
        for window in sequence.windows(2) {
            assert!(window[0].can_advance_to(&window[1]));
        }
        // No skipping ahead.
        assert!(!HandoffState::Preparing.can_advance_to(&HandoffState::SourceStopped));
        // No going backward.
        assert!(!HandoffState::Checkpointed.can_advance_to(&HandoffState::Preparing));
    }

    #[test]
    fn failure_is_reachable_from_any_in_progress_state_but_not_from_terminal_states() {
        let failed = HandoffState::Failed {
            phase: FailedPhase::Transfer,
            reason: "disk full".to_owned(),
        };
        assert!(HandoffState::SourceStopped.can_advance_to(&failed));
        assert!(!HandoffState::Complete.can_advance_to(&failed));
        assert!(!failed.can_advance_to(&HandoffState::Preparing));
    }

    #[test]
    fn complete_is_only_reachable_from_target_verified() {
        assert!(HandoffState::TargetVerified.can_advance_to(&HandoffState::Complete));
        assert!(!HandoffState::TargetStarting.can_advance_to(&HandoffState::Complete));
        assert!(!HandoffState::SourceStopped.can_advance_to(&HandoffState::Complete));
    }

    #[test]
    fn transaction_id_parses_only_relay_shaped_input() {
        let generated = TransactionId::generate();
        assert!(TransactionId::parse(generated.as_str()).is_ok());
        assert!(TransactionId::parse("../../etc/passwd").is_err());
        assert!(TransactionId::parse("").is_err());
        assert!(TransactionId::parse("has spaces").is_err());
    }
}
