name: Debug ps

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: macos-latest
    steps:
      - name: ps -Eww
        run: |
          set -x
          ps -Eww -o command= ; echo "exit1=$?"
          ps -ww -o command= | head -5 ; echo "exit2=$?"
          ps -E -o command= | head -5 ; echo "exit3=$?"
          sw_vers
          uname -a
